---
name: Destroy all workflow

on:
  workflow_dispatch:
    branches:
      - master
      - staging
      - develop


jobs:
  aws_cdk:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install CDK       
        shell: bash
        run: |
          npm install -g typescript
          npm install -g aws-cdk
          npm install
      - name: Destroy
        shell: bash
        run: "cdk destroy --all --force"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          CDK_SERVICE_NAME: ${{ secrets.CDK_SERVICE_NAME }}
