
---
name: CDK workflow

on:
  push:
    branches:
      - master
      - staging
      - develop


jobs:
  aws_cdk:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name       
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/setup-node@v2
        with:
        node-version: '15'
      - name: Install CDK       
      shell: bash
      run: |
        npm install -g typescript
        npm install -g aws-cdk
      id: extract_branch
      - name: cdk synth
        shell: bash
        run: "cdk synth --all"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          CDK_SERVICE_NAME: ${{ secrets.CDK_SERVICE_NAME }}
      - name: cdk diff
        shell: bash
        run: "cdk diff ${CDK_SERVICE_NAME}-service-${{ steps.extract_branch.outputs.branch }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          CDK_SERVICE_NAME: ${{ secrets.CDK_SERVICE_NAME }}
      - name: cdk deploy
        shell: bash
        run: "cdk deploy ${CDK_SERVICE_NAME}-service-${{ steps.extract_branch.outputs.branch }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          CDK_SERVICE_NAME: ${{ secrets.CDK_SERVICE_NAME }}